RVL_OPTS = '-ipa file'
EGG_OPTS = '-ipa function -rostr'
REL_OPTS = '-ipa file -rostr -sdata 0 -sdata2 0'
NW4R_OPTS = '-ipa file -inline auto -rostr -O4,p'

compile_source("source/rvl/trk/rvlTrkMem.c", "out/rvlTrkMem.o", '4199_60831', RVL_OPTS)
compile_source("source/rvl/arc/rvlArchive.c", "out/rvlArchive.o", '4199_60831', RVL_OPTS)
compile_source("source/rvl/mem/rvlMemHeap.cpp", "out/rvlMemHeap.o", '4199_60831', RVL_OPTS)
compile_source("source/rvl/mem/rvlMemExpHeap.c", "out/rvlMemExpHeap.o", '4199_60831', RVL_OPTS)
compile_source("source/rvl/mem/rvlMemFrmHeap.cpp", "out/rvlMemFrmHeap.o", '4199_60831', RVL_OPTS)
compile_source("source/rvl/mem/rvlMemUnitHeap.cpp", "out/rvlMemUnitHeap.o", '4199_60831', RVL_OPTS)
compile_source("source/rvl/mem/rvlMemAllocator.cpp", "out/rvlMemAllocator.o", '4199_60831', RVL_OPTS)
compile_source("source/rvl/mem/rvlMemList.cpp", "out/rvlMemList.o", '4199_60831', RVL_OPTS)
compile_source("source/rvl/mtx/rvlMtx.c", "out/rvlMtx.o", '4199_60831', RVL_OPTS)
compile_source("source/rvl/mtx/rvlMtx2.c", "out/rvlMtx2.o", '4199_60831', RVL_OPTS)
compile_source("source/rvl/mtx/rvlVec.c", "out/rvlVec.o", '4199_60831', RVL_OPTS)
compile_source("source/rvl/mtx/rvlQuat.c", "out/rvlQuat.o", '4199_60831', RVL_OPTS)
compile_source("source/rvl/so/soCommon.c", "out/soCommon.o", '4199_60831', RVL_OPTS)
compile_source("source/rvl/so/soBasic.c", "out/soBasic.o", '4199_60831', RVL_OPTS)

compile_source("source/gamespy/darray.c", "out/darray.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/hashtable.c", "out/hashtable.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/md5c.c", "out/md5c.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/common/revolution/gsSocketRevolution.c", "out/gsSocketRevolution.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/common/gsAvailable.c", "out/gsAvailable.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/common/revolution/gsUtilRevolution.c", "out/gsUtilRevolution.o", '4199_60831', RVL_OPTS)
#compile_source("source/gamespy/common/gsPlatformUtil.c", "out/gsPlatformUtil.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/common/gsCore.c", "out/gsCore.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/common/gsUdpEngine.c", "out/gsUdpEngine.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/common/gsXML.c", "out/gsXML.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gp/gp.c", "out/gp.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gp/gpi.c", "out/gpi.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gp/gpiBuddy.c", "out/gpiBuddy.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gp/gpiBuffer.c", "out/gpiBuffer.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gp/gpiCallback.c", "out/gpiCallback.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gp/gpiConnect.c", "out/gpiConnect.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gp/gpiInfo.c", "out/gpiInfo.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gp/gpiKeys.c", "out/gpiKeys.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gp/gpiOperation.c", "out/gpiOperation.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gp/gpiPeer.c", "out/gpiPeer.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gp/gpiProfile.c", "out/gpiProfile.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gp/gpiSearch.c", "out/gpiSearch.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gp/gpiTransfer.c", "out/gpiTransfer.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gp/gpiUnique.c", "out/gpiUnique.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gp/gpiUtility.c", "out/gpiUtility.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gt2/gt2Auth.c", "out/gt2Auth.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gt2/gt2Buffer.c", "out/gt2Buffer.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gt2/gt2Callback.c", "out/gt2Callback.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gt2/gt2Connection.c", "out/gt2Connection.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gt2/gt2Main.c", "out/gt2Main.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gt2/gt2Socket.c", "out/gt2Socket.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/gt2/gt2Utility.c", "out/gt2Utility.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/qr2/qr2.c", "out/qr2.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/qr2/qr2RegKeys.c", "out/qr2RegKeys.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/ghttp/ghttpBuffer.c", "out/ghttpBuffer.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/ghttp/ghttpCallbacks.c", "out/ghttpCallbacks.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/ghttp/ghttpCommon.c", "out/ghttpCommon.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/ghttp/ghttpPost.c", "out/ghttpPost.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/serverbrowsing/sb_crypt.c", "out/sb_crypt.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/serverbrowsing/sb_queryengine.c", "out/sb_queryengine.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/serverbrowsing/sb_server.c", "out/sb_server.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/serverbrowsing/sb_serverlist.c", "out/sb_serverlist.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/serverbrowsing/sb_serverbrowsing.c", "out/sb_serverbrowsing.o", '4199_60831', RVL_OPTS)
compile_source("source/gamespy/sake/sakeMain.c", "out/sakeMain.o", '4199_60831', RVL_OPTS)

compile_source("source/nw4r/math/mathTriangular.cpp", "out/mathTriangular.o", '4201_127', NW4R_OPTS)
compile_source("source/nw4r/math/mathTypes.cpp", "out/mathTypes.o", '4201_127', NW4R_OPTS)
compile_source("source/nw4r/g3d/g3d_camera.cpp", "out/g3d_camera.o", '4201_127', NW4R_OPTS)
compile_source("source/nw4r/g3d/g3d_fog.cpp", "out/g3d_fog.o", '4201_127', NW4R_OPTS)
compile_source("source/nw4r/ut/utList.cpp", "out/utList.o", '4201_127', NW4R_OPTS)

compile_source("source/dwc/common/dwc_error.c", "out/dwc_error.o", '4199_60831', RVL_OPTS)

compile_source("source/egg/core/eggAllocator.cpp", "out/eggAllocator.o", '4201_127', EGG_OPTS + " -use_lmw_stmw=on ")
compile_source("source/egg/core/eggArchive.cpp", "out/eggArchive.o", '4201_127', EGG_OPTS + " -use_lmw_stmw=on ")
compile_source("source/egg/core/eggDisposer.cpp", "out/eggDisposer.o", '4201_127', EGG_OPTS)
compile_source("source/egg/core/eggExpHeap.cpp", "out/eggExpHeap.o", '4201_127', EGG_OPTS + " -use_lmw_stmw=on  ")
compile_source("source/egg/core/eggGraphicsFifo.cpp", "out/eggGraphicsFifo.o", '4201_127', EGG_OPTS)
compile_source("source/egg/core/eggHeap.cpp", "out/eggHeap.o", '4201_127', EGG_OPTS + " -ipa file -use_lmw_stmw=on  ")
compile_source("source/egg/math/eggQuat.cpp", "out/eggQuat.o", '4201_127', EGG_OPTS)
compile_source("source/egg/core/eggStreamDecomp.cpp", "out/eggStreamDecomp.o", '4201_127', EGG_OPTS)
# compile_source("source/egg/core/eggSystem.cpp", "out/eggSystem.o", '4201_127', EGG_OPTS)
compile_source("source/egg/core/eggThread.cpp", "out/eggThread.o", '4201_127', EGG_OPTS)
compile_source("source/egg/core/eggUnitHeap.cpp", "out/eggUnitHeap.o", '4201_127', EGG_OPTS + " -use_lmw_stmw=on  ")
compile_source("source/egg/core/eggVideo.cpp", "out/eggVideo.o", '4201_127', EGG_OPTS+ " -use_lmw_stmw=on  ")
compile_source("source/egg/math/eggVector.cpp", "out/eggVector.o", '4201_127', EGG_OPTS)
# compile_source("source/egg/core/eggXfb.cpp", "out/eggXfb.o", '4201_127', EGG_OPTS)
# compile_source("source/egg/core/eggXfbManager.cpp", "out/eggXfbManager.o", '4201_127', EGG_OPTS)

"""
StaticR.rel
"""

compile_source("source/game/ui/MessageGroup.cpp", "out/MessageGroup.o", '4201_127', REL_OPTS)
compile_source("source/game/ui/ControlGroup.cpp", "out/ControlGroup.o", '4201_127', REL_OPTS)
compile_source("source/game/ui/UIControl.cpp", "out/UIControl.o", '4201_127', REL_OPTS)
compile_source("source/game/jmap/JmpResourceCourse.cpp", "out/JmpResourceCourse.o", '4201_127', REL_OPTS)
