#pragma once

#include <rvl/gx.h>

#include <rk_types.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum VIMode { VI_INTERLACE, VI_NON_INTERLACE, VI_PROGRESSIVE } VIMode;

typedef enum VIRegion {
  VI_NTSC,
  VI_PAL,
  VI_MPAL,
  VI_DEBUG,
  VI_DEBUG_PAL,
  VI_EURGB60
} VIRegion;

typedef enum VIXFBMode { VI_XFBMODE_SF, VI_XFBMODE_DF } VIXFBMode;

// Credit: YAGCD
typedef enum VITVMode {
#define MAKE_TV_MODE(region, mode) ((region << 2) + mode)
  VI_TVMODE_NTSC_INT = MAKE_TV_MODE(VI_NTSC, VI_INTERLACE),
  VI_TVMODE_NTSC_DS = MAKE_TV_MODE(VI_NTSC, VI_NON_INTERLACE),
  VI_TVMODE_NTSC_PROG = MAKE_TV_MODE(VI_NTSC, VI_PROGRESSIVE),

  VI_TVMODE_PAL_INT = MAKE_TV_MODE(VI_PAL, VI_INTERLACE),
  VI_TVMODE_PAL_DS = MAKE_TV_MODE(VI_PAL, VI_NON_INTERLACE),

  VI_TVMODE_EURGB60_INT = MAKE_TV_MODE(VI_EURGB60, VI_INTERLACE),
  VI_TVMODE_EURGB60_DS = MAKE_TV_MODE(VI_EURGB60, VI_NON_INTERLACE),
  VI_TVMODE_EURGB60_PROG = MAKE_TV_MODE(VI_EURGB60, VI_PROGRESSIVE),

  VI_TVMODE_MPAL_INT = MAKE_TV_MODE(VI_MPAL, VI_INTERLACE),
  VI_TVMODE_MPAL_DS = MAKE_TV_MODE(VI_MPAL, VI_NON_INTERLACE),
  VI_TVMODE_MPAL_PROG = MAKE_TV_MODE(VI_MPAL, VI_PROGRESSIVE),

  VI_TVMODE_DEBUG_INT = MAKE_TV_MODE(VI_DEBUG, VI_INTERLACE),

  VI_TVMODE_DEBUG_PAL_INT = MAKE_TV_MODE(VI_DEBUG_PAL, VI_INTERLACE),
  VI_TVMODE_DEBUG_PAL_DS = MAKE_TV_MODE(VI_DEBUG_PAL, VI_NON_INTERLACE)
#undef MAKE_TV_MODE
} VITVMode;

void VIInit();
void VISetBlack(int black);
void VIConfigure(const GXRenderModeObj* obj);
void VIFlush();
void VIWaitForRetrace();

int VIGetDTVStatus();
unsigned int VIGetTvFormat();

void *VIGetNextFrameBuffer();
void VISetNextFrameBuffer(void *);

#ifdef __cplusplus
}
#endif
