---
on:
  push:
    paths:
      - 'clang_check.py'
      - '**.h'
      - '**.c'
      - '**.hpp'
      - '**.cpp'
  pull_request:
    paths:
      - 'clang_check.py'
      - '**.h'
      - '**.c'
      - '**.hpp'
      - '**.cpp'
name: Check
jobs:
  clang_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Run clang_check.py
        run: python clang_check.py
