---
on: [push, pull_request]
name: Lint
jobs:
  lint-clang-format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Check clang-format version
        run: clang-format-12 --version

      - name: Verify formatting
        run: |
          find source -type f \
            \( \
                 -name '*.h' \
              -o -name '*.c' \
              -o -name '*.hpp' \
              -o -name '*.cpp' \
            \) \
            -exec clang-format-12 --dry-run --Werror {} +
